/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d8e3fa",
        "surface-bright": "#f9f9ff",
        "on-secondary-container": "#5f6365",
        "on-surface": "#111c2c",
        "on-background": "#111c2c",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-fixed": "#dde1ff",
        "outline-variant": "#c4c5d6",
        "primary-container": "#1b43ba",
        "primary": "#002c94",
        "secondary-fixed": "#e0e3e5",
        "tertiary-fixed-dim": "#c6c6c7",
        "inverse-surface": "#263142",
        "surface-container-low": "#f0f3ff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#0a39b2",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#454747",
        "outline": "#747685",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-container-high": "#dee8ff",
        "primary-fixed-dim": "#b7c4ff",
        "secondary-container": "#dde0e2",
        "secondary-fixed-dim": "#c4c7c9",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-container": "#e7eeff",
        "on-secondary-fixed": "#181c1e",
        "background": "#f9f9ff",
        "on-tertiary-container": "#c0c1c1",
        "surface-tint": "#3154ca",
        "inverse-primary": "#b7c4ff",
        "surface-container-highest": "#d8e3fa",
        "on-primary-fixed": "#001452",
        "inverse-on-surface": "#ebf1ff",
        "tertiary-container": "#4d4f4f",
        "surface-dim": "#cfdaf1",
        "on-surface-variant": "#444654",
        "secondary": "#5b5f61",
        "on-secondary-fixed-variant": "#434749",
        "on-primary-container": "#b0beff",
        "on-primary": "#ffffff",
        "surface": "#f9f9ff",
        "tertiary": "#363839",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "status-green": "#10b981",
        "status-red": "#ef4444",
        "status-success": "#16a34a",
        "status-error": "#dc2626"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-sm": "0.5rem",
        "header-height": "64px",
        "sidebar-width": "240px",
        "margin-page": "2rem",
        "gutter-md": "1.5rem",
        "stack-md": "1rem"
      },
      fontFamily: {
        "status-label": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "status-label": ["12px", { "lineHeight": "16px", "fontWeight": "700" }],
        "headline-lg-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
